name: Deploy GitHub Page
on:
  push:
    branches:
      - main
jobs:
  deploy-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts --legacy-peer-deps

      - name: Build story book artifacts
        run: npm run storybook:build

      - name: Commit changes for git hub doc site
        run: |
          rm -f docs/*.js*
          rsync -a ./storybook-static/ ./docs/
          git add docs
          git config --global user.name 'GitHub Page Bot'
          git config --global user.email 'gh-page-bot@users.noreply.github.com'
          git commit -am "docs(gh-page): update storybook [skip ci]"
          git push
